# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nicole Moran
tagline:          'Web Developer'
description:      'Pay no attention to the coder behind the curtain.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Nicole Moran'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
