# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nicole Moran
tagline:          'Web Developer'
description:      'Pay no attention to the coder behind the curtain.'
url:              http://nicolemoran.github.io
baseurl:          /

author:
  name:           'Nicole Moran'
  url:            https://www.google.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nicolemoran/nicolemoran.github.io
