# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nicole Moran
tagline:          'Web Developer'
description:      'ncmartist@gmail.com'
url:              https://nicolemoran.github.io
baseurl:          /about

author:
  name:           'Nicole Moran'
  url:            https://www.google.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nicolemoran/nicolemoran.github.io
